version: '3'
services:
  frontend:
    image: mustapha69/frontend-tunisairmob:${BUILD_ID}
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production

  backend:
    image: mustapha69/backend-tunisairmob:${BUILD_ID}
    ports:
      - "8083:8083"
    environment:
      - NODE_ENV=production
